PREFIX wd:       <http://www.wikidata.org/entity/>
PREFIX wdt:      <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd:       <http://www.bigdata.com/rdf#>

SELECT DISTINCT ?item ?itemLabel ?value ?website
WHERE {
  ?item wdt:P31/wdt:P279* wd:Q1248784 ;
        wdt:P17 wd:Q183 ;
        wdt:P2044 ?value .
  FILTER (?value > 100)
  OPTIONAL { ?item wdt:P856 ?website }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
ORDER BY DESC(?value) ?item
LIMIT 20
